export function normalizarCategoria(categoria) {
  return categoria
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '');
}

export function obterIconeCategoria(categoria) {
  const icones = {
    // Categorias financeiras principais
    salario: '💵',
    freelancer: '🧑‍💻',
    pix_recebido: '💸',
    alimentacao: '🍽️',
    contas: '💡',
    transporte: '🚌',
    lazer: '🎨',
    saude: '🩺',
    educacao: '📚',
    compras: '🛍️',
    outros: '📦',
    Receita: '💰',
    Despesa: '🛒',
    Alimentação: '🍽️',
    Outros: '📦',
    Lazer: '🎨',
    Freelancer: '🧑‍💻',
    receita: '💰',
    despesa: '🛒',

    // Gatilhos extras já existentes (mantive os seus!)
    tarefa: '📝',
    trabalho: '💼',
    remedio: '💊',
    conta: '💸',
    pix: '💸',
    limpeza: '🧹',
    skincare: '💅',
    cronograma: '💇‍♀️',
    exercicio: '🏃‍♀️',
    meditacao: '🧘‍♀️',
    leitura: '📖',
    filme: '🎬',
    serie: '📺',
    organizacao: '🗂️',
    aniversario: '🎂',
    meta: '🎯',
    motivacao: '💖',
    conquista: '🏆',
    devocional: '🙏',
    familia: '👨‍👩‍👧',
    filho: '🧒',
    pessoal: '🌸',
    profissional: '💼',
    financeira: '💰',
    financa: '💰',
    higiene: '🧼',
    farmacia: '🏥',
    Farmacia: '🏥',
    pet: '🐶',
    cozinha: '🍳',
    banheiro: '🛁',
    sala: '🛋️',
    quarto: '🛏️',
    lavanderia: '🧺',
    quintal: '🌿',
    varanda: '🌤️',
    escritorio: '💻',
    garagem: '🚗',
    corredor: '🚪',
    entrada: '🏠',
    escola: '🏠',
    cabelo: '💇‍♀️',
    esfoliacao: '🧖‍♀️',
    hidratacao: '💧',
    tratamento: '🧪',
    maquiagem: '💄',
    tonico: '🌿',
    protetor: '🌞',
    noturno: '🌙',
    diurno: '☀️',
    alimento: '🛒',
    curso: '📜',
    autocuidado: '🛁',
    maternidade: '👶',
    economia: '🏦',
    desafio: '🔥',
    sonho: '🌈',
    viagem: '✈️',
    passeio: '🧳',
    hobby: '🎲',
    espiritual: '🕊️',
    voluntariado: '👐',
    objetivo: '📌',
    foco: '🎯',
    planner: '🗓️',
    inspiracao: '🌟',

    // Exames
    exame_de_sangue: '💉',
    ginecologica: '🧫',
    exame_de_vista: '👁️',
    consulta_dentista: '🦷',
    ultrassom: '🖼️',
    raio_x: '🩻',

    // Alimentos detalhados
    bebida: '🧃',
    roupas: '👚',
    papelaria: '📎',
    cafe_da_manha: '🥐',
    almoco: '🍛',
    jantar: '🍽️',
    sobremesa: '🍰',
    lanche: '🥪',
    frutas: '🍎',
    legumes: '🥕',
    verduras: '🥬',
    carnes: '🍗',
    peixe: '🐟',
    frango: '🍖',
    massas: '🍝',
    arroz_feijao: '🍚',
    sopas: '🥣',
    congelados: '🧊',
    marmita: '🍱',
    saudavel: '💚',
    especial: '⭐',
    favorito: '❤️',
    guloseima: '🍫',
    padaria: '🍞',
    cafe: '☕',

    // Limpeza detalhada
    faxina: '🧹',
    banheiro_limpeza: '🚽',
    cozinha_limpeza: '🍳',
    roupas_limpeza: '👚',
    sala_limpeza: '🛋️',
    quarto_limpeza: '🛏️',
    varanda_limpeza: '🌿',
    geladeira: '🧊',
    organizar: '📦',

    // Skincare
    hidratacao_skincare: '💧',
    limpeza_skincare: '🫧',
    esfoliacao_skincare: '🧼',
    mascara: '🎭',
    protetor_solar: '🌞',
    tonico_skincare: '🍃',
    rotina_skincare: '🧖‍♀️',
    serum: '🧪',
    creme: '🧴',
    gel: '🫧',
    skincare: '🪞',
    espuma: '🫧',
    esfoliante: "🧽",
    oleo: "🛢️",

    // Cronograma capilar
    reconstrucao: '💪',
    nutricao: '🥑',
    hidratar_cabelo: '🌊',
    pre_poo: '🫙',
    finalizacao: '🎀',
    cronograma_capilar: '🧴',

    // Cronograma Estudo
    revisao: '📚',
    pratica: '🧠',
    aula: '👩‍🏫',

    // Remédios
    antibiotico: '💊',
    analgesico: '🩹',
    suplemento: '🍯',
    vitamina: '🍊',
    colirio: '👁️',
    inalacao: '💨',
    xarope: '🧃',
    horario: '⏰',
    remedios: '💊',
    remedio: '💊',
    remedio_com_acento: '💊',
    remedios_com_acento: '💊',
    consulta: '🩺',
    exame: '🧪',
    retorno: '🔁',
  };

  if (!categoria) return '❓';

  const chave = normalizarCategoria(categoria).replace(/\s+/g, '_');
  return icones[chave] || '📌';
}
